from .cic import build_downsampling_cic as build_downsampling_cic
from .simple import build_downsampling_simple as build_downsampling_simple
from .subsampling import build_downsampling_subsampling as build_downsampling_subsampling
