[[plugins]]
name = "thresholding"
version = "0.1"
api_version = "0.1"
target_runtime = "verilog"
target_platform = "FPGA"
generated = [
  "const",
  "mov_avg_norm",
  "mov_avg_pow2",
  "mean_avg",
  "steady_return"
]
static_files = []
