from .downsampling import SettingsDownSampling as SettingsDownSampling
from .downsampling import DefaultSettingsDownSampling as DefaultSettingsDownSampling
from .downsampling import DownSampling as DownSampling
